name: Terraform GitHub Organization Setup

on:
  workflow_dispatch: # esecuzione manuale
  push: # opzionale: esegui su push
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./ # o la tua cartella TF, se diversa

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        env:
          TF_VAR_github_token: ${{ secrets.GH_ADMIN_TOKEN }}
          TF_VAR_github_org: ${{ secrets.GH_ORG }}

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        env:
          TF_VAR_github_token: ${{ secrets.GH_ADMIN_TOKEN }}
          TF_VAR_github_org: ${{ secrets.GH_ORG }}
