name: Setup GitHub Organization

on:
  workflow_dispatch: # lancio manuale dal tab Actions

jobs:
  setup-org:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install requests
        run: pip install requests

      - name: Run GitHub setup script
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}
          GITHUB_ORG: ${{ secrets.GH_ORG }}
        run: python scripts/day2/gh_api/github_setup.py
