name: Migrate Django

on:
  push:
  pull_request:

env:
  DJANGO_SETTINGS_MODULE: 'icsc_db2_api.config.settings'
  SOCIAL_AUTH_CLIENT_ID: '3d770df0-7657-4325-97e4-0dd72d9137a3'
  SOCIAL_AUTH_AZUREAD_TENANT_OAUTH2_KEY: '3d770df0-7657-4325-97e4-0dd72d9137a3'
  SOCIAL_AUTH_AZUREAD_TENANT_ID: 'organizations'
  ICSC_DB2_API_DATABASE_URL: 'db2://db2inst1:password@db2:50000/DEVDB?PCONNECT=True^&ATOMIC_REQUESTS=True^&currentschema=db2inst1'
  ICSC_DB2_API_DATABASE_TEST_SCHEMA: 'test'
  ICSC_DB2_API_POSTGRES_DATABASE_URL: 'psql://postgres:@db:5432/db2api'
  ICSC_DB2_API_POSTGRES_DATABASE_TEST_NAME: 'test'
  ICSC_DB2_API_ALLOWED_HOSTS: '127.0.0.1,localhost'
  ICSC_DB2_API_DEBUG: 1
  ICSC_DB2_API_MODELS_ARE_MANAGED: 1
  PYTHONPATH: "./src"
  POSTGRES_DB: "test"
  POSTGRES_PASSWORD: ""
  POSTGRES_USER: "postgres"
  POSTGRES_HOST_AUTH_METHOD: trust
  LICENSE: accept
  DBNAME: "devdb"
  DB2INST1_PASSWORD: "password"

jobs:
  test:
    name: pytest
    runs-on: ubuntu-latest

    steps:
      - name: pytest
        run: |
          echo "Job dei test"
          echo "$PDM_USER\n$PDM_PASSWORD $PDM_USER | pdm install -v"
          pip install pdm==2.16.1
          pdm config python.use_venv false
          printf "$PDM_USER\n$PDM_PASSWORD" "$PDM_USER" | pdm install --dev -v
          sleep 120
          pdm run pytest -vvv -s --disable-warnings --cov-report=html --create-db --cov-config=.coveragerc --cov=src/icsc_db2_api tests
        env:
          SOCIAL_AUTH_AZUREAD_TENANT_OAUTH2_SECRET: ${{ secrets.SOCIAL_AUTH_AZUREAD_TENANT_OAUTH2_SECRET }}
          ICSC_DB2_API_SECRET_KEY: ${{ secrets.ICSC_DB2_API_SECRET_KEY }}

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: output/test/code-coverage.html